INSERT INTO `knowledge_point` VALUES (1, '串联电路', '几个电路元件沿着单一路径互相连接，每个连接点最多只连接两个元件，此种连接方式称为串联', '以串联方式连接的电路称为串联电路', '学习目标', 1, 'fwagrfgftg', 'fsdfertr', '参考资料', '备注');
INSERT INTO `knowledge_point` VALUES (2, '电路', '电路（英语：Electrical circuit）或称电子回路', '电路（英语：Electrical circuit）或称电子回路，是由电气设备和元器件, 按一定方式连接起来，为电荷流通提供了路径的总体', '了解', 4, 'gsdgreser', 'sgfsdftgre', '参考资料', '备注');
INSERT INTO `knowledge_point` VALUES (3, '电', '电是静止或移动的电荷所产生的物理现象', '电是静止或移动的电荷所产生的物理现象。在大自然里，电的机制给出了很多众所熟知的效应，例如', '了解电学的基本概念', 3, 'gsdgre', 'sdfgsrgf', '参考资料', '备注');
INSERT INTO `knowledge_point` VALUES (4, '直流', '几个电路元件沿着单一路径互相连接，每个连接点最多只连接两个元件，此种连接方式称为串联', '以串联方式连接的电路称为串联电路', '学习目标', 5, 'srsdfg', 'fdsgref', '参考资料', '备注');
INSERT INTO `knowledge_point` VALUES (5, '并联电路', '并联电路便是电路连接的另外一种形式', '并联从字面上理解便是并在一起的连接，有两个以上的电阻，', '掌握并联电路的电压和电流规律', 5, ' ', ' ', 'https://www.dgxue.com/chuji/zhiliudian/clbldl/365.html', '备注');
INSERT INTO `knowledge_point` VALUES (6, '短路', '短路（Short circuit）是指在正常电路中电势不同的两点不正确', '过大的电流有可能导致电路损坏，过热，火灾或爆炸。', '掌握短路时电压和电流的规律', 4, ' ', ' ', 'https://zh.wikipedia.org/wiki/%E7%9F%AD%E8%B7%AF', '备注');
INSERT INTO `knowledge_point` VALUES (7, '断路', '断路（开路）是指处于电路没有闭合开关', '即整个电路在某处断开的状态。', '掌握断路时电压和电流的规律', 4, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (8, '欧姆定律', '导电体两端的电压与通过导电体的电流成正比', '在同一电路中，通过某段导体的电流跟这段导体两端的电压成正比，跟这段导体的电阻成反比', '掌握电压、电流、电阻之间的关系', 5, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (9, '电动势', '即电子运动的趋势，能够克服导体电阻对电流的阻力', '电源区中也存在着电阻，称为电源的内阻', '掌握电动势与电势差的区别', 2, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (10, '电压', '电压（voltage），也称作电势差或电位差', '电压的方向规定为从高电位指向低电位的方向', '掌握电动势与电势差的区别', 2, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (11, '串联电路电压规律', '串联电路两端总电压等于各部分电路两端电压和', '串联电路两端总电压等于各部分电路两端电压和', '会计算', 5, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (12, '并联电路电压规律', '并联电路各支路两端电压相等，且等于电源电压。', '并联电路各支路两端电压相等，且等于电源电压。', '记忆公式', 5, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (13, '电阻', '电阻（Resistance，通常用“R”表示），是一个物理量', '导体的电阻越大，表示导体对电流的阻碍作用越大。', '熟悉电阻的特性', 3, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (14, '超导现象', '某些物质在很低的温度时，电阻就变成了零。这就是超导现象', '某些物质在很低的温度时，电阻就变成了零。这就是超导现象', '熟悉电阻的特性', 2, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (15, '伏安特性曲线', '伏安特性曲线图常用纵坐标表示电流I、横坐标表示电压U', '伏安特性曲线是针对导体的，也就是耗电元件，图像常被用来研究导体电阻的变化规律', '绘制曲线', 3, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (16, '电功率', '电流在单位时间内做的功叫做电功率', '电流在单位时间内做的功叫做电功率', '会计算', 5, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (17, '额定电压', '额定电压是指电气设备长时间正常工作时的最佳电压，额定电压也称为标称电压', '额定电压是指电气设备长时间正常工作时的最佳电压，额定电压也称为标称电压', '了解', 2, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (18, '焦耳定律', '额定电压是指电气设备长时间正常工作时的最佳电压，额定电压也称为标称电压', '额定电压是指电气设备长时间正常工作时的最佳电压，额定电压也称为标称电压', '了解', 2, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (19, '电阻率', '电阻率是用来表示各种物质电阻特性的物理量', '', '了解', 1, 'doc', 'video', 'reference', '备注');
INSERT INTO `knowledge_point` VALUES (20, '电流热效应', '电流通过导体时电能转化成热，把这种现象叫做电流热效应', '电流通过导体时电能转化成热，把这种现象叫做电流热效应', '了解', 2, 'doc', 'fsdfsd', NULL, '备注');
INSERT INTO `knowledge_point` VALUES (21, '电能', '电能，是指使用电以各种形式做功(即产生能量)的能力', '有直流电能、交流电能、高频电能等。这几种电能均可相互转换', '了解', 1, '', '', '', '');
INSERT INTO `knowledge_point` VALUES (22, '电场', '电场是电荷及变化磁场周围空间里存在的一种特殊物质', '电场这种物质与通常的实物不同，它不是由分子原子所组成，但它是客观存在的，', '了解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (23, '电荷', '电荷（electric charge） ，带正负电的基本粒子，称为电荷', '电荷（electric charge） ，带正负电的基本粒子，称为电荷', '了解', 1, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (24, '直流电压', '电压值会随时间的增长而改变，但是方向不随时间变化的电压叫脉动直流电压', '如手电筒电池两端和灯泡两端的电压都是直流电压。', '区别直流电压和交流电压', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (25, '正弦交流电', '大小和方向随时间作有规律变化的电压和电流称为交流电，又称交变电流', '正弦交流电是随时间按照正弦函数规律变化的电压和电流。由于交流电的大小和方向都是随时间不断变化的', '了解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (26, '导线', '导线，指的是用作电线电缆的材料，工业上也指电线', '导线，指的是用作电线电缆的材料，工业上也指电线', '了解', 1, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (27, '导体', '导体中存在大量可自由移动的带电粒子称为载流子', '导体中存在大量可自由移动的带电粒子称为载流子', '了解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (28, '正电荷', '用丝绸摩擦过的玻璃棒所带的电荷叫做正电荷', '质子是正电荷，而正电荷不一定是质子，对应的电子即是负电荷', '了解', 1, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (29, '负电荷', '把毛皮摩擦过的橡胶棒所带的电荷叫做负电荷', '电荷间相互作用的规律：同种电荷互相排斥，异种电荷互相吸引。', '了解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (30, '电荷量', '电荷量:简称电量', '定义q₁、q₂为电荷的电荷量,即电荷量定义来源于库伦定律公式。', '了解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (31, '自由电荷', '自由电荷是一种等效概念', '自由电荷是一种等效概念，通常指存在于物质内部，在外电场作用下能作定向运动的电荷。', '理解', 2, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (32, '电流的磁效应', '安培定则', '安培定则', '掌握', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (33, '电流', '电流（英语：electric current）是电荷的流动', '电流的大小称为电流强度，是指单位时间内通过导线某一截面的电荷，每秒通过1库仑的电荷量称为1安培', '会运用', 5, NULL, NULL, NULL, NULL);
INSERT INTO `knowledge_point` VALUES (34, '安培定律', '安培定律（英语：Ampère\'s circuital law），又称安培环路定律', '载流循环所产生的磁场方向可以使用右手定则来判断。其方法为将拇指外的四根手指向手掌弯的方向视为磁场方向，则拇指所指的方向即为电流的方向', '会使用右手定则', 5, '', NULL, NULL, NULL);
